- loader/src/mapping.rs
- renovate.json5
Setup renovate for dependency updates
> Setup renovate

- kernel/src/lib.rs
> fix: actually run test suite

- libs/linked-list/src/lib.rs
This change implements `IntoIter` for `List<T>`.
> feat(linked-list): Implement `IntoIter`

- libs/mmu/src/frame_alloc/buddy.rs
This change simplifies the implementation of the buddy allocators allocate routine using Rusts iterator combinators to make it more readable.
> reactor: simplify `BuddyAllocator::allocate_inner` implementation

- loader/src/arch/riscv64.rs
This change resets more registers into a known sane state on boot (masking interrupts, disabling the MMU, etc) in case a previous stage boot loader left the hart in a weird state.
> fix(loader/riscv64): reset more registers on boot

- .github/workflows/ci.yml
- Cargo.lock
- flake.lock
- justfile
- kernel/src/arch/riscv64/mod.rs
This updates various nix packages, most importantly the QEMU version
> chore: update package version

- Cargo.lock
- Cargo.toml
- kernel/src/vm/address_space.rs
- kernel/src/vm/mod.rs
- libs/wavltree/Cargo.toml
- loader/src/page_alloc.rs
Updates the rand crates
closes #255 #256
> update rand crates

- libs/backtrace/src/lib.rs
This change removed the already broken support for short backtraces since it would sometimes cause the entire backtrace to not print at all.
> fix(backtrace): remove broken support for short backtraces

- kernel/src/vm/address_space.rs
- kernel/src/vm/mod.rs
> chore: implement `Debug` for `AddressSpace`

- kernel/src/arch/riscv64/device/cpu.rs
- kernel/src/time/clock.rs
Makes the printed debug info about each CPU look nicer
> chore: pretty print CPU info

- kernel/src/scheduler/mod.rs
Since each task *might* have a different address space, we must switch to the correct one before actually executing any code that accesses non-global memory. This PR makes the scheduler switch before polling (not that this is likely not the final way forward for this, instead this should happen *inside* the future being polled, but that's a future todo)
> fix: switch to correct address space in scheduler

- kernel/src/main.rs
- kernel/src/shell.rs
This cleans up the shell output a bit, as well as adding a (somewhat) nice banner
> chore: shell banner & cleanup

- manual/src/SUMMARY.md
- manual/src/building/boot-args.md
This adds a few notes on boot arguments.
> docs: boot args

- libs/unwind2/src/frame.rs
This PR adds basic support for DWARF expressions to `unwind2`
> feat(unwind2): support DWARF expression

- kernel/src/arch/riscv64/fiber.rs
- kernel/src/arch/riscv64/mod.rs
- kernel/src/fiber.rs
- kernel/src/main.rs
- kernel/src/scheduler/mod.rs
This PR redoes the fiber implementation, this time in a less janky fashion based on https://github.com/Amanieu/corosensei
> feat: fiber impl second version

- flake.nix
> Add `wasm-tools` to nix dev shell

- build/xtask/src/cmds/lldb.rs
- build/xtask/src/main.rs
- build/xtask/src/qemu.rs
actually implement `xtask lldb` for connect lldb to a k23 instance
> fix: `xtask lldb`

- Cargo.lock
- Cargo.toml
- kernel/Cargo.toml
> upgrade deps

- Cargo.lock
- kernel/src/main.rs
- kernel/src/mem/frame_alloc/mod.rs
- kernel/src/metrics.rs
- kernel/src/scheduler/mod.rs
- kernel/src/tracing/registry.rs
- libs/cpu-local/Cargo.toml
- libs/cpu-local/src/collection.rs
- libs/cpu-local/src/lib.rs
Adds the `CpuLocal` collection type to the `cpu-local` crate
> feat: cpu-local collection

- Cargo.lock
- justfile
- libs/async-exec/Cargo.toml
- libs/async-exec/src/executor.rs
- libs/async-exec/src/lib.rs
- libs/async-exec/src/loom.rs
- libs/async-exec/src/park.rs
- libs/async-exec/src/park/parker.rs
- libs/async-exec/src/park/parking_lot.rs
- libs/async-exec/src/scheduler.rs
- libs/async-exec/src/scheduler/steal.rs
- libs/async-exec/src/sync.rs
- libs/async-exec/src/task.rs
- libs/async-exec/src/task/builder.rs
- libs/async-exec/src/task/id.rs
- libs/async-exec/src/task/join_handle.rs
- libs/async-exec/src/task/state.rs
- libs/async-exec/src/time.rs
- libs/mpsc-queue/src/lib.rs
- libs/mpsc-queue/src/loom.rs
This PR will move the async task executor out of the kernel into a standalone crate, where it can be better tested. Additionally it will be broken out into components that can be verified & tested individually.
This PR is non-complete but passes basic tests and further work can happen in subsequent PRs.
This closes #422
> wip: async executor base

- libs/async-exec/src/executor.rs
- libs/async-exec/src/park/parking_lot.rs
clean up the ParkingLot signature a bit
> refactor: ParkingLot with_capacity

- libs/spin/src/mutex.rs
This fixes a bug/unexpected behavior and failing Miri test. Previously `try_lock` would use
`compare_exchange_weak` under the hood, but that can spuriously fail *even if* the lock is fully unlocked. This PR changes `try_lock` to use the regular `compare_exchange` and introduces `try_lock_weak` to keep the old behavior (useful if `try_lock_weak` is called in loops)
> fix: use strong comparison in `Mutex::try_lock` and introduce `Mutex::try_lock_weak`

- release-plz.toml
Produce correct git tags for wavltree
> fix release plz tag name

- kernel/src/mem/trap_handler.rs
This PR fixes the page fault handling functionality (load, store, and instruction faults). 
Currently it is using kernel address space, and have not added support for x86_64, but it is suffice to pass the `just test-riscv64` test.
> Fix: Page fault handling
