JonasKruckenberg/k23

- Cargo.lock
- kernel/src/arch/riscv64/mod.rs
- kernel/src/tests.rs
- libs/kstd/Cargo.toml
- libs/kstd/src/sync/lazy_lock.rs
- libs/kstd/src/sync/mod.rs
- libs/kstd/src/sync/once.rs
- libs/kstd/src/sync/once_lock.rs
- loader/src/arch/riscv64.rs
- loader/src/main.rs
This renamed the previous `Once` one-time initialization primitive to `OnceLock`, adds a new type called `Once` that provides lower-level one-time functionality and a `LazyLock` type that provides an on-demand lazy initialization container.
> feat(kstd): `Once`, `OnceLock`, and `LazyLock`

- libs/kstd/src/backtrace/mod.rs
- libs/kstd/src/lib.rs
- libs/kstd/src/panicking.rs
- libs/kstd/src/unwinding/mod.rs
- libs/kstd/src/unwinding/unwinder.rs
- libs/ktest/macros/Cargo.toml
- loader/api/macros/Cargo.toml
This change adds the `kstd::backtrace` module which uses the unwind machinery introduced in previous changes to provide a `trace_unsynchronized` function, which in-turn allows us to capture a stack trace at a given point.
Backtraces are currently unsymbolized, i.e. only the instruction pointer, stack pointer and symbol address are given since no_std symbolization is a larger endeavor and using `addr2line` on the command line already works
> feat(kstd): `trace_unsynchronized` and panic backtraces

- libs/vmm/src/elf.rs
This change corrects a bug in the `vmm` elf loading logic, where BSS sections larger than one page would not be correctly mapped.
> fix(vmm): correctly map additional BSS pages

- Cargo.lock
- configs/riscv64-qemu.toml
- configs/riscv64gc-k23-none-kernel.json
- justfile
- loader/Cargo.toml
- loader/src/kaslr.rs
- loader/src/kconfig.rs
- loader/src/main.rs
- loader/src/paging.rs
- loader/src/payload.rs
This change builds off of the support for position independent code added in #93 to implement KASLR in the `loader` crate.
This is done by using the `rng-seed`  provided by the FDT (i.e. by the previous stage loader) to seed a `ChaCha20`-based random number generator. The generator is then used to generate a cryptographically secure base address for the payload.
Note that a page-aligned address is chosen in a window between `PHYS_OFFSET` and the highest possible, i.e. `PHYS_OFFSET..(u64::MAX - kernel_size)` which is around `2^25` depending on the kernel size (the entropy will get smaller as the kernel grows).
> feat: Kernel Address Space Layout Randomization (KASLR)

- Cargo.lock
- kernel/Cargo.toml
- libs/panic/Cargo.toml
- libs/panic/src/panicking.rs
This change removes the backtrace feature from the `panic` crate and the backtrace printing from the default panic hook. Instead a custom panic hook should be used.
> refactor: remove backtrace feature from panic

- kernel/src/start.rs
- loader/api/src/info.rs
- loader/src/boot_info.rs
- loader/src/main.rs
This changes passes information about the location of the payload in physical memory to the payload itself so it can perform introspection into its own elf file if desired (e.g. to access eh_frame info for stack unwinding for debug info for symbolization).
> feat(loader-api): pass physical payload location

- Cargo.lock
- libs/ktest/src/lib.rs
- libs/leb128/Cargo.toml
- libs/leb128/src/lib.rs
- libs/wasm-encoder/Cargo.toml
- libs/wasm-encoder/src/core/code.rs
- libs/wasm-encoder/src/lib.rs
- libs/wast/Cargo.toml
- libs/wast/src/component/binary.rs
- libs/wast/src/encode.rs
- libs/wast/src/lexer.rs
- libs/wast/src/lib.rs
- libs/wast/src/token.rs
The wast & wasm-encoder crates vendored from the `wasm-tools` repo weren't playing nice withe the rest of the setup, this PR cleans them up a bit and makes esp. tests work with the ktest setup
> refactor: cleanup wast crate

- justfile
Running `just` commands on Windows failed due to shell issues which are fixed in this PR
> Windows compatibility for Justfile added

- justfile
Well, embarrassingly the setup until now never correctly propagated the release profile to the loader itself. So even when the kernel was built in release mode, the loader will still compiled in debug mode, which of course made the compression horrifically slow.
fixes: #114 and makes #146 obsolete
> fix: actually propagate release profile to loader

- libs/wavltree/src/lib.rs
The  `cursor`/`cursor_mut` where ambiguously named and broken anyway, so this change "replaces" them with `root` and `root_mut` methods that still return a cursor over the whole tree, but make it clear where they start (in the middle)
> refactor: replace broken `cursor`/`cursor_mut` with `root`/`root_mut` methods

- Cargo.lock
- Cargo.toml
- libs/linked-list/Cargo.toml
- libs/linked-list/src/lib.rs
This PR implements an intrusively linked list based on [cordyceps](https://github.com/hawkw/mycelium/tree/main/cordyceps) for use in e.g. a more efficient buddy allocator.
> feat(linked-list): intrusive linked list

- Cargo.lock
- libs/pmm/Cargo.toml
- libs/pmm/src/frame_alloc/buddy.rs
- libs/pmm/src/frame_alloc/mod.rs
- libs/pmm/src/lib.rs
- loader/src/vm.rs
This change implements a basic buddy frame allocator. Compared to the existing BitMap & Bump allocators, this new allocator supports efficient allocation alignments other than PAGE_SIZE
> feat(pmm): buddy frame allocator

- loader/src/boot_info.rs
This adds a sanity assertion to the creation code for a `BootInfo` that ensures the memory region slice doesn't overflow its maximum size.
> chore: `BootInfo` memory creation sanity check

- kernel/src/lib.rs
- kernel/src/vm.rs
- libs/pmm/src/address_space.rs
- libs/pmm/src/frame_alloc/bootstrap.rs
- libs/pmm/src/frame_alloc/buddy.rs
- libs/pmm/src/frame_alloc/mod.rs
- loader/src/arch/riscv64.rs
- loader/src/boot_info.rs
- loader/src/machine_info.rs
- loader/src/vm.rs
This PR partially reverts usage of the new `BuddyAllocator` in the loader, it's tendency to scatter allocations across the managed range - while a benefit in normal operation - turns out to be a downside in the loader where we need to collect up free and used regions to pass them to the kernel. The `BuddyAllocator` produced hundreds of regions even for small physmem sizes (3G of physmem resulted in ~1024 regions), which drastically limited max physmem size we were able to deal with.
This change reintroduces the `BumpAllocator` as `BootstrapAllocator` and while it produces less efficient mappings for the kernel heap, I think in practice that is acceptable. The overhead turns out to not be *that* significant and we can always deal with it later.
> Revert: `BuddyAllocator` usage in loader

- kernel/src/arch/riscv64/vm.rs
- libs/pmm/src/frame_alloc/buddy.rs
- loader/src/arch/riscv64.rs
- loader/src/boot_info.rs
- loader/src/kernel.rs
- loader/src/main.rs
- loader/src/vm.rs
This change actually allocates and copies the kernel ELF into a freshly allocated physical memory region so it gets properly accounted for in later physical memory allocators
> fix: allocate and copy kernel ELF

- kernel/src/arch/riscv64/mod.rs
- kernel/src/machine_info.rs
- kernel/src/start.rs
- kernel/src/vm.rs
- libs/riscv/src/register/mod.rs
- libs/riscv/src/register/time.rs
- loader/src/machine_info.rs
- loader/src/main.rs
This change restructures the kernels `MachineInfo` struct into a `MachineInfo` and a TLS `HartLocalMachineInfo`. The reason for doing so is that `HartLocalMachineInfo` now tracks the hart-local `timebase-frequency` property required for converting the Riscv logical realtime clock value into a wall-clock value.
It also introduces the necessary low-level `riscv::register::time` primitives to read the realtime clock register.
> feat(kernel): parse `timebase-frequency` into  hart local state

- kernel/src/arch/riscv64/vm.rs
- kernel/src/start.rs
- kernel/src/vm.rs
- libs/ktest/src/run.rs
- loader/api/src/info.rs
- loader/src/arch/riscv64.rs
- loader/src/boot_info.rs
This PR reports the full `physmap` region through the `BootInfo` structure instead of just the start address, since recreating it from the FDT would be much more expensive.
> reafctor: report the full physmem map region not just the start address

- libs/pmm/src/frame_alloc/buddy.rs
This change adds a canary value field to the `FreeArea` buddy allocator entry that is used to detect already initialized free areas and panic if areas are already managed by an allocator
> fix(pmm): Detect already managed areas in `BuddyAlloc` through canary value

- kernel/src/time.rs
- loader/src/arch/riscv64.rs
- loader/src/boot_info.rs
This brings back the behaviour of `BumpAllocator::lower_bound` of preventing the loader from overriding its own memory in a more maintainable way by building up a second array of available memory regions that are filtered to exclude the loader memory
> fix(loader): prevent frame allocator from handing out loader memory

- kernel/src/arch/mod.rs
- kernel/src/arch/riscv64/mod.rs
- kernel/src/arch/riscv64/setjmp_longjmp.rs
- kernel/src/arch/riscv64/trap_handler.rs
- kernel/src/arch/riscv64/vm.rs
This PR adds a *safer* wrapper for `setjmp` called `call_with_setjmp` that helps to prevent LLVM miscompilations such as happened [here](https://github.com/JonasKruckenberg/k23/actions/runs/12529118111/job/34944386599#step:6:666) where LLVM emitted a store immediate 1 instead of a load-add-store sequence for this code snippet:
```rust
let mut c = 0;
let mut buf = JumpBuf::new();
let r = setjmp(ptr::from_mut(&mut buf));
c += 1; // on opt-lvl >=1 this becomes a store immediate 1 instead of a load-add-store
// because LLVM rightly assumes that this point will only be reached once per frame
if r == 0 {
assert_eq!(c, 1);
longjmp(ptr::from_mut(&mut buf), 1234567);
}
assert_eq!(c, 2);
assert_eq!(r, 1234567);
```
(see on godbolt [here](https://godbolt.org/z/Wxbo1qPE5))
If you force `c` into a …
> fix(kernel): prevent `setjmp`/`longjmp` miscompilations through `call_with_setjmp`

- kernel/src/time.rs
- loader/api/src/info.rs
- loader/src/arch/riscv64.rs
- loader/src/boot_info.rs
This collects the ticks value as early on system startup as possible (literally the first instruction in the loader) so we can accurately measure boot times.
> feat(loader): collect boot ticks

- libs/mmu/src/arch/riscv64.rs
This change actually makes use of the `asid` param passed to `get_active_pgtable`. It asserts that the currently active ASID matches the passed ASID as a sanity check.
> fix(mmu/riscv64): assert correct ASID when loading pgtables

- Cargo.lock
- kernel/Cargo.toml
- kernel/src/error.rs
`onlyerror` specifically in the kernel crate has caused weird infinite name resolution times for RustRover :/ it doesn't do that much anyways so just remove it from the kernel.
> refactor(kernel): remove `onlyerror`

- justfile
This change reenables SMP in QEMU. The kernel should be fully SMP ready and future development should have SMP enabled to make sure support doesn't regress.
This change also sets up a basic NUMA topology, where 8 cpus are equally grouped into 2 nodes and memory is also equally divided between the two nodes.
> chore: QEMU reenable SMP & NUMA

- loader/api/src/config.rs
- loader/src/vm.rs
As part of reenabling SMP by default, this change adds guard pages below each harts stack allocation to catch kernel stack overflows.
> feat(loader): include guard pages in stack allocations

- kernel/src/vm/mod.rs
- loader/src/arch/riscv64.rs
- loader/src/vm.rs
This change fixes a bug with the TLS mapping code, which caused the kernel TLS region per hart to be incorrectly calculated. By fixing it we also reduced the TLS allocation memory consumption by a factor of ~`PAGE_SIZE` (4096).
> fix(loader/vm): correctly calculate and map TLS regions

- Cargo.lock
- Cargo.toml
- kernel/src/panic.rs
- libs/addr2line/CHANGELOG.md
- libs/addr2line/Cargo.toml
- libs/addr2line/LICENSE-APACHE
- libs/addr2line/LICENSE-MIT
- libs/addr2line/README.md
- libs/addr2line/src/frame.rs
- libs/addr2line/src/function.rs
- libs/addr2line/src/lazy.rs
- libs/addr2line/src/lib.rs
- libs/addr2line/src/line.rs
- libs/addr2line/src/lookup.rs
- libs/addr2line/src/unit.rs
- libs/backtrace/Cargo.toml
- libs/backtrace/src/lib.rs
This change - in the spirit of `backtrace` and `unwind2` - vendors the `addr2line` crate to make it more compatible with k23s needs, in particular upgrading its rustc version and making use of k23 synchronization primitives.
> chore: vendor `addr2line` crate

- kernel/src/vm/address_space.rs
This implements `AddressSpace:: map_specific` which can be used to map a `Vmo` at a specific virtual address instead of the potentially randomly chosen location of `AddressSpace::map`.
> feat: implement `AddressSpace:: map_specific`

- kernel/src/vm/address_space.rs
- kernel/src/vm/address_space_region.rs
- kernel/src/vm/frame_alloc/mod.rs
- kernel/src/vm/frame_list.rs
- kernel/src/vm/paged_vmo.rs
- libs/mmu/src/address_space.rs
- libs/wavltree/src/cursor.rs
Implements the `AddressSpace::unmap(range: Range<VirtualAddress>)` method which can be used to unmap previously established mappings in the address space.
I'm not super happy with the current solution, as it silently ignores attempts to unmap already unmapped regions, but it will suffice as a first version.
> feat: implement `AddressSpace::unmap`

- kernel/src/vm/address_space.rs
- kernel/src/vm/address_space_region.rs
- kernel/src/vm/mod.rs
This change makes the `AddressSpaceRegion` name optional, as it is used for debugging anyway and regions might not actually have any associated name.
> chore: optional `AddressSpaceRegion` name

- Cargo.lock
- justfile
- kernel/src/allocator.rs
- kernel/src/main.rs
- kernel/src/panic.rs
- kernel/src/vm/address_space_region.rs
- kernel/src/vm/frame_alloc/mod.rs
- kernel/src/vm/mod.rs
- kernel/src/vm/paged_vmo.rs
- loader/Cargo.toml
- loader/api/Cargo.toml
- loader/api/src/info.rs
- loader/src/arch/mod.rs
- loader/src/arch/riscv64.rs
- loader/src/boot_info.rs
- loader/src/error.rs
- loader/src/frame_alloc.rs
- loader/src/kernel.rs
- loader/src/machine_info.rs
- loader/src/main.rs
- loader/src/mapping.rs
- loader/src/page_alloc.rs
This PR begins the process of removing the `mmu` crate. It has served us well, but as the virtual memory subsystem in the kernel begins to mature, the `loader` and `kernel` requirements for hardware memory management are diverging.
This PR then starts and removed the `mmu` crate as a dependency of the `loader`. This introduces some code duplication, but this appears more sensible to me.
> refactor(loader): replace usage of `mmu`

- kernel/src/main.rs
- kernel/src/metrics.rs
This PR introduces the facilities around kernel counters, as the next debugging primitive after logging. Kernel counters are per-hart, `u64` counters that can be used to track events across the kernel. 
This PR only introduces the ability to declare counters, followup work should make use of them across the kernel (specifically the vm subsystem) and even later followup work should implement the ability to read out counters via some shell.
> feat(kernel): kernel metrics

- kernel/src/vm/address_space.rs
- kernel/src/vm/mmap.rs
- kernel/src/vm/mod.rs
- kernel/src/vm/vmo/mod.rs
This PR implements a basic version of `MmapSlice` which essentially is a handle to an `AddressSpaceRegion` for use in other parts of the kernel. Just like the vm subsystem it currently doesn't support partial mutation but importantly it doesn't automatically unmap its region on drop, so it is not a complete RAII wrapper.
It is expected that the `InstanceAllocator` will take care of managing the lifecycle. For this reason `MmapSlice` doesn't expose a real constructor, instead `InstanceAllocator` should allocate the `AddressSpaceRegion` in the `AddressSpace` and then construct a `MmapSlice` using `MmapSlice::from_raw`.
> feat(kernel): `Mmap`

- kernel/src/arch/riscv64/vm.rs
This PR adds debug validation to the RISCV flags, to ensure the flags align with the spec:
" Writable pages must also be marked readable; the contrary combinations are reserved for future use."
> chore(kernel/vm): validate RISCV flags

- kernel/src/vm/address_space.rs
- kernel/src/vm/error.rs
Fixes an issue where the `AddressSpace::page_fault` method would panic if called with a virtual address not belonging to the address space. After this PR the method will return an error.
> fix: don't panic on non address space address

- kernel/src/executor/mod.rs
- kernel/src/executor/scheduler/multi_thread/idle.rs
- kernel/src/executor/scheduler/multi_thread/worker.rs
- kernel/src/main.rs
- kernel/src/util/parking_spot.rs
This PR fixes a "bug" where the initial test task for each HART would be scheduled through the global run queue and therefore distributed randomly among the workers. This is usually what we want (therefore "bug" in quotes) but not in this specific case where we want each hart to run their own task.
The long-term proper solution would be to a add CPU affinity to tasks, but this PR adds a callback after the worker was initialized so we can spawn the task then.
> fix: add callback `executor::run` to spawn hart-local tasks

- kernel/src/vm/provider.rs
- kernel/src/vm/vmo.rs
This fixes a stupid bug where THE ZERO FRAME provider would always return the zero frame even for write mappings. This of course isn't great and led to all memory mappings being mapped to the same Frame which obviously meant horrific data corruption.
> fix: don't share the zero frame for write

- kernel/src/cmdline.rs
- kernel/src/main.rs
- kernel/src/tracing/filter.rs
- kernel/src/tracing/mod.rs
- libs/fdt/src/error.rs
- libs/fdt/src/lib.rs
- libs/fdt/src/parser.rs
- manual/src/building/debugging.md
This PR ports a simplified subset of the `tracing-subscriber` `EnvFilter` logic so that we can finally filter log messages dynamically!
The bootarg is called `log` and can be used with the same syntax as `Envfilter` (just without the support for filtering by message fields).
```sh
just run "" --append "log=trace,cranelift_codegen=off"
```
at long last closes #11
> feat: allow filtering of log messages

- kernel/src/task/join_handle.rs
- kernel/src/task/mod.rs
This PR fixes a bug in the `JoinHandle` Future code that would swallow failures from awaited tasks, such as panics and cancellations and always report `Ok(())`
> fix: correctly return from `JoinHandle` when task fails

- Cargo.lock
- kernel/src/main.rs
- kernel/src/panic.rs
- libs/backtrace/Cargo.toml
- libs/backtrace/src/lib.rs
This fixes #300 by eagerly capturing all frames when constructing a backtrace. This change also brings back the wrapping of the kernel main function in `catch_unwind` to fix unwinding code
> fix: eagerly capture frames in `Backtrace::capture`

- Cargo.lock
- Cargo.toml
- kernel/Cargo.toml
- kernel/src/backtrace/mod.rs
- kernel/src/backtrace/symbolize.rs
- kernel/src/main.rs
- kernel/src/panic.rs
This moves the `backtrace` crate into the kernel since it wasn't useful outside of it anyway and this streamlines the API.
> refactor: move backtracing logic into `kernel`

- kernel/src/arch/riscv64/trap_handler.rs
- kernel/src/backtrace/mod.rs
- kernel/src/panic.rs
- libs/unwind2/src/lang_items.rs
- rust-toolchain.toml
This allows panicking in the trap handler, which while not desired is a good debugging feature to have
> fix: panics in trap handler

- kernel/src/arch/riscv64/mod.rs
- kernel/src/arch/riscv64/vm.rs
- kernel/src/vm/address.rs
- kernel/src/vm/address_space.rs
- kernel/src/vm/bootstrap_alloc.rs
- kernel/src/vm/mod.rs
This fixes a bug where a user address space could generate invalid non-canonical addresses because the max range was incorrectly configured
> fix: user aspace max range

- kernel/src/arch/riscv64/asid_allocator.rs
- kernel/src/arch/riscv64/mod.rs
- kernel/src/arch/riscv64/vm.rs
- kernel/src/wasm/engine.rs
- kernel/src/wasm/instance_allocator.rs
- kernel/src/wasm/store.rs
Instead of the previous default implementation, this correctly initializes the instance allocator from an ASID allocator and root RNG maintained by the engine.
> feat: correctly initialize InstanceAllocator

- kernel/src/arch/riscv64/trap_handler.rs
- kernel/src/scheduler/mod.rs
Fixes a panic in `Scheduler::current_task` when the function gets called outside of the worker loop.
> fix: dont panic in `Scheduler::current_task`

- kernel/src/vm/user_mmap.rs
- kernel/src/wasm/runtime/memory.rs
- kernel/src/wasm/runtime/mmap_vec.rs
- kernel/src/wasm/runtime/owned_vmcontext.rs
This PR makes the WASM `Memory` and `OwnedVMContext` actually use the `UserMmap`
> refactor: use `UserMmap` throughout wasm code

- kernel/src/arch/riscv64/vm.rs
- kernel/src/main.rs
- kernel/src/vm/address_space.rs
- kernel/src/vm/address_space_region.rs
- kernel/src/vm/frame_alloc/mod.rs
- kernel/src/vm/mod.rs
- kernel/src/vm/provider.rs
- kernel/src/vm/user_mmap.rs
- kernel/src/vm/vmo.rs
- kernel/src/wasm/instance_allocator.rs
- kernel/src/wasm/mod.rs
- kernel/src/wasm/store.rs
In preparation for state unification, this PR turns all previously freestanding frame allocation functions `frame_alloc::*` into methods of the `FrameAllocator` struct.
> refactor: turn frame allocation functions into `FrameAllocator` methods

- kernel/src/arch/riscv64/mod.rs
- kernel/src/vm/user_mmap.rs
- kernel/src/wasm/func.rs
- kernel/src/wasm/runtime/instance.rs
- loader/src/arch/riscv64.rs
This change makes it so the RISCV `SUM` (Supervisor User Memory access) bit is set at startup and never unset. This will allow the more complex interwoven memory usage of WASM engines (i.e. allowing access to the shared stack memory and VMContext object)
> chore: always leave `SUM` bit enabled

- kernel/src/vm/user_mmap.rs
- kernel/src/wasm/runtime/owned_vmcontext.rs
Eagerly commit all pages of an `OwnedVMContext` upon creation (we should even pin them in the future) since we need that memory immediately for initialization.
> fix: eagerly commit `OwnedVMContext`

- Cargo.lock
- Cargo.toml
- kernel/src/wasm/runtime/instance.rs
This adds `tracing::instrument` statements to all vmctx init functions since these are critical we'll need as much insight as possible.
> chore: instrument vmctx init functions

- kernel/src/vm/address_space.rs
- kernel/src/wasm/runtime/instance.rs
This PR makes sure we're in the right address space when beginning to initialize the instance
> fix: activate address space before vmctx init

- kernel/src/wasm/compile/mod.rs
actually resolve relocations even when debug assertions are disabled. *sigh*
> fix: actually resolve relocations

- loader/src/arch/riscv64.rs
- loader/src/mapping.rs
This temporary PR allows user mode WASM to run on the kernel stack as well
> wip: allow usermode programs to access kernel stacks

- kernel/src/wasm/instance_allocator.rs
This removes the `Drop` assertion from the placeholder instance allocator. I assumed originally that the instance allocator should be the last place to drop its address space reference, but when running inside the scheduler, the last reference is actually the one kept by the task struct.
> fix: don't panic on `InstanceAllocator` drop

- kernel/src/arch/riscv64/trap_handler.rs
- kernel/src/fiber.rs
- kernel/src/main.rs
- kernel/src/wasm/func.rs
- kernel/src/wasm/mod.rs
This PR builds off the previous one to actually expose and async `call` method for WASM functions.
> feat: run WASM asynchronously

- kernel/src/arch/riscv64/device/plic.rs
- kernel/src/util/either.rs
- kernel/src/util/mod.rs
- kernel/src/util/zip_eq.rs
- kernel/src/wasm/cranelift/code_translator.rs
This PR moves the `Either` and `ZipEq` iterator utilities into the `util` module.
> chore: move iterator utilities into `util`

- kernel/src/arch/riscv64/device/plic.rs
- kernel/src/error.rs
- kernel/src/shell.rs
- kernel/src/util/either.rs
- kernel/src/util/maybe_uninit.rs
- kernel/src/util/mod.rs
- kernel/src/util/zip_eq.rs
- kernel/src/wasm/cranelift/code_translator.rs
- kernel/src/wasm/cranelift/env.rs
- kernel/src/wasm/errors.rs
- kernel/src/wasm/func.rs
- kernel/src/wasm/global.rs
- kernel/src/wasm/indices.rs
- kernel/src/wasm/instance.rs
- kernel/src/wasm/memory.rs
- kernel/src/wasm/mod.rs
- kernel/src/wasm/runtime/vmcontext.rs
- kernel/src/wasm/table.rs
- kernel/src/wasm/translate/mod.rs
- kernel/src/wasm/translate/type_convert.rs
- kernel/src/wasm/translate/types.rs
- kernel/src/wasm/utils.rs
- kernel/src/wasm/values.rs
This PR implements the `TypedFunc` type and related machinery. `TypedFunc` allows us to front-load the type checking of WASM functions and then on subsequent calls benefit from Rusts compile-time checks again. `TypedFunc` can also optimize its argument and result lowering/lifting.
`TypedFunc` should be the primary means of interacting with WASM functions.
> feat: `TypedFunc`

- kernel/src/arch/riscv64/mod.rs
- kernel/src/wasm/func.rs
- kernel/src/wasm/mod.rs
- kernel/src/wasm/runtime/vmcontext.rs
This change moves the details of calling the array-call trampoline to the `arch` module, since jumping to user mode is very architecture specific.
> chore: move WASM array-call code to arch module

- kernel/src/wasm/func.rs
- kernel/src/wasm/mod.rs
This cleans up the `wasm::func` module and adds explanatory comments
> refactor: cleanup func module

- kernel/src/backtrace/mod.rs
- kernel/src/backtrace/print.rs
- kernel/src/bootargs.rs
- kernel/src/main.rs
- kernel/src/panic.rs
This PR adds configurable support for shorter backtraces. Shorter backtraces only print symbols between the `__rust_begin_short_backtrace` and `__rust_end_short_backtrace` frames cutting out the quite verbose frames related to unwinding and backtracing itself.
This behavior can be configured through a boot argument like so `backtrace=short` for short (the new default) backtraces and `backtrace=full` for more verbose full backtraces.
Use with QEMU like so `just run "" --append "backtrace=full"`
> feat: allow configurable short backtrace

- kernel/src/vm/address_space_region.rs
This adds the address space region name to the fault info logging
> chore: include the aspace region name in page fault info

- kernel/src/bootargs.rs
- manual/src/building/boot-args.md
The previous bootargs separator `,` conflicted with the separator for log arguments which isn't great. This PR changes the bootargs separator to `;`.
> fix: bootargs separator

- kernel/src/vm/frame_alloc/arena.rs
- loader/src/arch/riscv64.rs
- loader/src/boot_info.rs
- loader/src/frame_alloc.rs
- loader/src/main.rs
- loader/src/mapping.rs
This change brings back non-contiguous physical allocations in places where it makes sense to have them. This helps to make better use of memory especially as we approach the maxmimum system memory.
> fix: use non-contiguous allocations wherever possible

- loader/src/main.rs
range ends are actually *exclusive* this fixes a debug assert that was incorrectly assuming the ends are inclusive
> fix: correctly check for overlapping memory regions

- loader/Cargo.toml
- loader/src/kernel.rs
- loader/src/main.rs
This moves some kernel parsing code around in the loader
> refactor: move kernel parsing code around

- kernel/src/main.rs
- kernel/src/mem/bootstrap_alloc.rs
- kernel/src/mem/frame_alloc/arena.rs
- kernel/src/mem/frame_alloc/mod.rs
- loader/src/frame_alloc.rs
This PR fixes two issues with the arena selection code:
1. When finding a hole to unsuitably large we previously just forgot about the candidate region, essentially wasting it completely. This PR allocates an intermediate vec for all candidates and pushes unsuitable candidates back into that list.
2. the region bounds adjustment code would override itself so that essentially a higher candidate region would completely override the previous arena bounds, essentially wasting the previous lower region
> fix: correctly select arena regions

- kernel/src/wasm/vm/const_eval.rs
The const eval stack allocation gets reused, so we need to make sure to correctly pop all values from it.
> fix: correctly pop all values from const eval stack

- kernel/src/mem/address_space.rs
Correctly use `align` in assertion instead of `size`
> fix: use alignment in assert

- kernel/src/mem/provider.rs
This fixe removes an incorrect assertion in the zero frame provider. When cloning the zero page into a writable, it receives a different identity, but was still provided by the provider, so freeing using should work too.
> fix: remove assert in zero frame provider

- kernel/src/arch/riscv64/trap_handler.rs
- kernel/src/scheduler/idle.rs
- kernel/src/scheduler/mod.rs
This PR fixes a regression in the `scheduler/park` code which would cause tasks to not be woken after timers or interrupts. While it would be great to use this in the future, I can't figure out the exact details of how to correctly do it right now
> fix: CPU wakeup regression

- Cargo.lock
- Cargo.toml
- kernel/Cargo.toml
- kernel/src/main.rs
- kernel/src/panic.rs
- kernel/src/wasm/store/mod.rs
- libs/abort/Cargo.toml
- libs/abort/src/lib.rs
- libs/cpu-local/Cargo.toml
- libs/cpu-local/src/destructors.rs
- libs/cpu-local/src/lib.rs
- libs/riscv/src/lib.rs
- libs/unwind2/Cargo.toml
- libs/unwind2/src/arch/riscv64.rs
- libs/unwind2/src/exception.rs
- libs/unwind2/src/lang_items.rs
- libs/unwind2/src/lib.rs
- loader/Cargo.toml
- loader/src/arch/mod.rs
- loader/src/panic.rs
Replaced abort functions across libraries with a centralized `abort` library. This centralized function will be unmangled, never inlined and can therefore be used as a breakpoint symbol.
> Introduce `abort` library and refactor abort handling

- libs/addr2line/src/lib.rs
- libs/backtrace/src/lib.rs
- libs/fdt/src/lib.rs
- libs/ksharded-slab/src/lib.rs
- libs/mpsc-queue/src/lib.rs
- libs/riscv/src/lib.rs
- libs/uart-16550/src/lib.rs
- libs/unwind2/src/lib.rs
- libs/wast/src/lib.rs
Update the crate `no_std` headers to make testing easier in the future
> chore: update crate `no_std` headers

- build/xtask/src/qemu.rs
This change hides the very verbose QEMU interrupt info from the output log
> hide qemu interrupt info

- build/xtask/src/build.rs
This PR fixes release builds. Previously the loader would include the debug kernel *even* when a release build was requested.
> fix: correctly include release kernel in release builds

- libs/spin/src/backoff.rs
- libs/spin/src/barrier.rs
- libs/spin/src/lazy_lock.rs
- libs/spin/src/once.rs
- libs/spin/src/once_lock.rs
- libs/spin/src/rw_lock.rs
This fixes the usage of `spin` types when compiling under loom
> fix: spin loom constructors

- Cargo.lock
- libs/async-exec/Cargo.toml
- libs/async-exec/benches/ping_pong.rs
- libs/async-exec/src/executor.rs
- libs/async-exec/src/sync.rs
- libs/async-exec/src/sync/oneshot.rs
- libs/async-exec/src/sync/wait_cell.rs
- libs/async-exec/src/task/state.rs
This PR adds an async `oneshot` channel, which can be used to transfer ownership of a value from one task to another.
> feat: async oneshot channel

- libs/panic-unwind2/src/lib.rs
Downcasting of panic payloads into `&str` or `String` was broken previously, this change brings it back.
> fix: correctly print panic messages

- kernel/src/arch/riscv64/device/cpu.rs
- kernel/src/arch/riscv64/trap_handler.rs
- kernel/src/scheduler/mod.rs
- kernel/src/tracing/mod.rs
- libs/cpu-local/src/collection.rs
- libs/cpu-local/src/lib.rs
- libs/ksharded-slab/src/tid.rs
- libs/panic-unwind2/src/panic_count.rs
- libs/wast/src/gensym.rs
Now that `cpu-local` statics don't run destructors anymore (#411) I realized the whole `with` construction is pretty unnecessary, there is no need to constrain the lifetime to the callback scope, as soon as the static is initialized it will live for `'static`.
This PR simplifies the cpu-local crate even further by just having `LocalKey` implement `Deref`.
> refactor: simplify cpu-local

- manual/src/overview.md
hehe
I almost feel bad opening such a dummy pr 
:trollface:
> docs: Fix typo of `earyl` -> `early`

- kernel/src/main.rs
- libs/kasync/src/executor.rs
- libs/kasync/src/executor/steal.rs
- libs/kasync/src/lib.rs
- libs/kasync/src/task.rs
- libs/kasync/src/task/builder.rs
- libs/kasync/src/time/sleep.rs
We cannot actually allocate tasks with an allocator other than the default global one, since we currently do not have the ability to free using a custom allocator.
> fix(kasync): remove `*.try_spawn_in` methods.

- libs/kasync/src/task.rs
- libs/kasync/src/task/state.rs
This change removes the `Schedulable` struct and streamlines the waker implementation.
> refactor(kasync): remove Schedulable and simplify waker code

- libs/unwind2/src/eh_action.rs
- libs/unwind2/src/error.rs
- libs/unwind2/src/lib.rs
This makes the `EHAction` parsing code more resilient and brings it closer to the stdlib implementation.
> wip: make `EHAction` more resilient

- Cargo.lock
- libs/kmem/Cargo.toml
- libs/kmem/src/access_rules.rs
- libs/kmem/src/address_space.rs
- libs/kmem/src/address_space/region.rs
- libs/kmem/src/addresses.rs
- libs/kmem/src/lib.rs
- libs/wavltree/src/cursor.rs
This change implements the basic `AddressSpace` API surface and initial `AddressSpaceRegion` tree that sits at its core.
> wip(kmem): AddressSpace API and AddressSpaceRegion tree
